Header header

# this is what we can see at the intersection:
string front
string right
string left 

# Each of these can be:
string NO_CAR='no_car_detected'
string SIGNAL_A='car_signal_A'
string SIGNAL_B='car_signal_B'
string SIGNAL_C='car_signal_C'

# Plus we can see the traffic light

string traffic_light_state
 
string NO_TRAFFIC_LIGHT='no_traffic_light'
string STOP='tl_stop'
string GO='tl_go'
string YIELD='tl_yield'

